apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: ebpf-new-daemon-set
    version: v1
  name: ebpf-new-daemon-set
  namespace: ebpf
spec:
  selector:
    matchLabels:
      name: ebpf-new-pod
      version: v1
  template:
    metadata:
      annotations:
      labels:
        name: ebpf-new-pod
        version: v1
      name: ebpf-new-pod
      namespace: ebpf
    spec:
      containers:
      - image: iad.ocir.io/idlcuhhknffw/ebpf-new:latest
        imagePullPolicy: Always
        name: ebpf-new
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /sys/kernel/debug
          name: debug
      hostPID: true
      hostNetwork: true
      imagePullSecrets:
      - name: ocirsecret
      volumes:
      - name: debug
        hostPath:
          path: /sys/kernel/debug
          type: Directory