apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    app: ebpf-new
    version: v1
  name: ebpf-new-pod
  namespace: ebpf
spec:
  containers:
    - image: iad.ocir.io/idlcuhhknffw/ebpf-new:latest
      imagePullPolicy: IfNotPresent
      name: ebpf-new
      resources: {}
      securityContext:
        privileged: true
      command: ['./run-ebpf-prog']
      volumeMounts:
      - mountPath: /sys/kernel/debug
        name: debug
  hostPID: true
  hostNetwork: true
  imagePullSecrets:
    - name: ocirsecret
  volumes:
  - name: debug
    hostPath:
      path: /sys/kernel/debug
      type: Directory